# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
- env:
  - CGO_ENABLED=0
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
brews:
  -
    name: pg_flame
    goarm: 6
    github:
      owner: mgartner
      name: homebrew-tap
    folder: Formula
    homepage: "https://github.com/mgartner/pg_flame"
    description: "A flamegraph generator for Postgres EXPLAIN ANALYZE output."
